export const products = [
  {
    id: 1,
    name: "a2 Step 1",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "./img/a2_s1.webp",
    price: 47.0,
    amount: 0,
  },
  {
    id: 2,
    name: "a2 Step 2",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "./img/a2_s2.webp",
    price: 43.8,
    amount: 0,
  },
  {
    id: 3,
    name: "a2 Step 3",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "./img/a2_s3.webp",
    price: 42.5,
    amount: 0,
  },
  {
    id: 4,
    name: "a2 Step 4",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "./img/a2_s4.webp",
    price: 41.3,
    amount: 0,
  },
  {
    id: 5,
    name: "Aptamil Gold Step 1",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "./img/aptamil_gold_s1.webp",
    price: 32.2,
    amount: 0,
  },
  {
    id: 6,
    name: "Aptamil Gold Step 2",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. ",
    img: "./img/aptamil_gold_s2.webp",
    price: 32.2,
    amount: 0,
  },
  {
    id: 7,
    name: "Aptamil Gold Step 3",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "./img/aptamil_gold_s3.webp",
    price: 29.2,
    amount: 0,
  },
  {
    id: 8,
    name: "Aptamil Gold Step 4",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    img: "./img/aptamil_gold_s4.webp",
    price: 29.2,
    amount: 0,
  },
];
